name: CI

# On workflows change, while we test.
# Run the script (add Downloads to frameworks)
# Create release, etc...

on:
  push:
    branches:
    - 'workflows*'
    tags:
    - 'v*'

jobs:
  build:
    name: Building release assets
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: xcode-select
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Delete release notes
      run: rm -f .build/release.md

    - name: Run build
      run: swift run

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: release.md
        draft: false
        prerelease: false

    - name: Upload vim Xcframework
      id: upload-release-vim-xcframework-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vim.xcframework.zip
        asset_name: vim.xcframework.zip
        asset_content_type: application/zip

    - name: Upload xxd Xcframework
      id: upload-release-xxd-xcframework-zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./xxd.xcframework.zip
        asset_name: xxd.xcframework.zip
        asset_content_type: application/zip
